/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreaClubRouteImport } from './routes/crea-club'
import { Route as CrewSlugRouteImport } from './routes/$crewSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as CrewSlugIndexRouteImport } from './routes/$crewSlug.index'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as CrewSlugWeeklyRouteImport } from './routes/$crewSlug.weekly'
import { Route as CrewSlugTmRouteImport } from './routes/$crewSlug.tm'
import { Route as CrewSlugTeamRouteImport } from './routes/$crewSlug.team'
import { Route as CrewSlugStagioniRouteImport } from './routes/$crewSlug.stagioni'
import { Route as CrewSlugProfileRouteImport } from './routes/$crewSlug.profile'
import { Route as CrewSlugPlayersRouteImport } from './routes/$crewSlug.players'
import { Route as CrewSlugLeaderboardRouteImport } from './routes/$crewSlug.leaderboard'
import { Route as CrewSlugDashboardRouteImport } from './routes/$crewSlug.dashboard'
import { Route as CrewSlugBlackMarketRouteImport } from './routes/$crewSlug.black-market'
import { Route as CrewSlugAzioniRouteImport } from './routes/$crewSlug.azioni'
import { Route as CrewSlugAdminRouteImport } from './routes/$crewSlug.admin'
import { Route as CrewSlugChampionshipIndexRouteImport } from './routes/$crewSlug.championship.index'
import { Route as CrewSlugPlayerIdRouteImport } from './routes/$crewSlug.player.$id'
import { Route as CrewSlugChampionshipTeamIdRouteImport } from './routes/$crewSlug.championship.$teamId'
import { Route as ApiPublicAdminPlayersRouteImport } from './routes/api/public/admin/players'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreaClubRoute = CreaClubRouteImport.update({
  id: '/crea-club',
  path: '/crea-club',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewSlugRoute = CrewSlugRouteImport.update({
  id: '/$crewSlug',
  path: '/$crewSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const CrewSlugIndexRoute = CrewSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrewSlugRoute,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperadminRoute,
} as any)
const CrewSlugWeeklyRoute = CrewSlugWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugTmRoute = CrewSlugTmRouteImport.update({
  id: '/tm',
  path: '/tm',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugTeamRoute = CrewSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugStagioniRoute = CrewSlugStagioniRouteImport.update({
  id: '/stagioni',
  path: '/stagioni',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugProfileRoute = CrewSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugPlayersRoute = CrewSlugPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugLeaderboardRoute = CrewSlugLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugDashboardRoute = CrewSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugBlackMarketRoute = CrewSlugBlackMarketRouteImport.update({
  id: '/black-market',
  path: '/black-market',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugAzioniRoute = CrewSlugAzioniRouteImport.update({
  id: '/azioni',
  path: '/azioni',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugAdminRoute = CrewSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugChampionshipIndexRoute =
  CrewSlugChampionshipIndexRouteImport.update({
    id: '/championship/',
    path: '/championship/',
    getParentRoute: () => CrewSlugRoute,
  } as any)
const CrewSlugPlayerIdRoute = CrewSlugPlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => CrewSlugRoute,
} as any)
const CrewSlugChampionshipTeamIdRoute =
  CrewSlugChampionshipTeamIdRouteImport.update({
    id: '/championship/$teamId',
    path: '/championship/$teamId',
    getParentRoute: () => CrewSlugRoute,
  } as any)
const ApiPublicAdminPlayersRoute = ApiPublicAdminPlayersRouteImport.update({
  id: '/api/public/admin/players',
  path: '/api/public/admin/players',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$crewSlug': typeof CrewSlugRouteWithChildren
  '/crea-club': typeof CreaClubRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/$crewSlug/admin': typeof CrewSlugAdminRoute
  '/$crewSlug/azioni': typeof CrewSlugAzioniRoute
  '/$crewSlug/black-market': typeof CrewSlugBlackMarketRoute
  '/$crewSlug/dashboard': typeof CrewSlugDashboardRoute
  '/$crewSlug/leaderboard': typeof CrewSlugLeaderboardRoute
  '/$crewSlug/players': typeof CrewSlugPlayersRoute
  '/$crewSlug/profile': typeof CrewSlugProfileRoute
  '/$crewSlug/stagioni': typeof CrewSlugStagioniRoute
  '/$crewSlug/team': typeof CrewSlugTeamRoute
  '/$crewSlug/tm': typeof CrewSlugTmRoute
  '/$crewSlug/weekly': typeof CrewSlugWeeklyRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/$crewSlug/': typeof CrewSlugIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/$crewSlug/championship/$teamId': typeof CrewSlugChampionshipTeamIdRoute
  '/$crewSlug/player/$id': typeof CrewSlugPlayerIdRoute
  '/$crewSlug/championship/': typeof CrewSlugChampionshipIndexRoute
  '/api/public/admin/players': typeof ApiPublicAdminPlayersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crea-club': typeof CreaClubRoute
  '/login': typeof LoginRoute
  '/$crewSlug/admin': typeof CrewSlugAdminRoute
  '/$crewSlug/azioni': typeof CrewSlugAzioniRoute
  '/$crewSlug/black-market': typeof CrewSlugBlackMarketRoute
  '/$crewSlug/dashboard': typeof CrewSlugDashboardRoute
  '/$crewSlug/leaderboard': typeof CrewSlugLeaderboardRoute
  '/$crewSlug/players': typeof CrewSlugPlayersRoute
  '/$crewSlug/profile': typeof CrewSlugProfileRoute
  '/$crewSlug/stagioni': typeof CrewSlugStagioniRoute
  '/$crewSlug/team': typeof CrewSlugTeamRoute
  '/$crewSlug/tm': typeof CrewSlugTmRoute
  '/$crewSlug/weekly': typeof CrewSlugWeeklyRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/$crewSlug': typeof CrewSlugIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/$crewSlug/championship/$teamId': typeof CrewSlugChampionshipTeamIdRoute
  '/$crewSlug/player/$id': typeof CrewSlugPlayerIdRoute
  '/$crewSlug/championship': typeof CrewSlugChampionshipIndexRoute
  '/api/public/admin/players': typeof ApiPublicAdminPlayersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$crewSlug': typeof CrewSlugRouteWithChildren
  '/crea-club': typeof CreaClubRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/$crewSlug/admin': typeof CrewSlugAdminRoute
  '/$crewSlug/azioni': typeof CrewSlugAzioniRoute
  '/$crewSlug/black-market': typeof CrewSlugBlackMarketRoute
  '/$crewSlug/dashboard': typeof CrewSlugDashboardRoute
  '/$crewSlug/leaderboard': typeof CrewSlugLeaderboardRoute
  '/$crewSlug/players': typeof CrewSlugPlayersRoute
  '/$crewSlug/profile': typeof CrewSlugProfileRoute
  '/$crewSlug/stagioni': typeof CrewSlugStagioniRoute
  '/$crewSlug/team': typeof CrewSlugTeamRoute
  '/$crewSlug/tm': typeof CrewSlugTmRoute
  '/$crewSlug/weekly': typeof CrewSlugWeeklyRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/$crewSlug/': typeof CrewSlugIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/$crewSlug/championship/$teamId': typeof CrewSlugChampionshipTeamIdRoute
  '/$crewSlug/player/$id': typeof CrewSlugPlayerIdRoute
  '/$crewSlug/championship/': typeof CrewSlugChampionshipIndexRoute
  '/api/public/admin/players': typeof ApiPublicAdminPlayersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$crewSlug'
    | '/crea-club'
    | '/login'
    | '/superadmin'
    | '/$crewSlug/admin'
    | '/$crewSlug/azioni'
    | '/$crewSlug/black-market'
    | '/$crewSlug/dashboard'
    | '/$crewSlug/leaderboard'
    | '/$crewSlug/players'
    | '/$crewSlug/profile'
    | '/$crewSlug/stagioni'
    | '/$crewSlug/team'
    | '/$crewSlug/tm'
    | '/$crewSlug/weekly'
    | '/superadmin/dashboard'
    | '/$crewSlug/'
    | '/superadmin/'
    | '/$crewSlug/championship/$teamId'
    | '/$crewSlug/player/$id'
    | '/$crewSlug/championship/'
    | '/api/public/admin/players'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crea-club'
    | '/login'
    | '/$crewSlug/admin'
    | '/$crewSlug/azioni'
    | '/$crewSlug/black-market'
    | '/$crewSlug/dashboard'
    | '/$crewSlug/leaderboard'
    | '/$crewSlug/players'
    | '/$crewSlug/profile'
    | '/$crewSlug/stagioni'
    | '/$crewSlug/team'
    | '/$crewSlug/tm'
    | '/$crewSlug/weekly'
    | '/superadmin/dashboard'
    | '/$crewSlug'
    | '/superadmin'
    | '/$crewSlug/championship/$teamId'
    | '/$crewSlug/player/$id'
    | '/$crewSlug/championship'
    | '/api/public/admin/players'
  id:
    | '__root__'
    | '/'
    | '/$crewSlug'
    | '/crea-club'
    | '/login'
    | '/superadmin'
    | '/$crewSlug/admin'
    | '/$crewSlug/azioni'
    | '/$crewSlug/black-market'
    | '/$crewSlug/dashboard'
    | '/$crewSlug/leaderboard'
    | '/$crewSlug/players'
    | '/$crewSlug/profile'
    | '/$crewSlug/stagioni'
    | '/$crewSlug/team'
    | '/$crewSlug/tm'
    | '/$crewSlug/weekly'
    | '/superadmin/dashboard'
    | '/$crewSlug/'
    | '/superadmin/'
    | '/$crewSlug/championship/$teamId'
    | '/$crewSlug/player/$id'
    | '/$crewSlug/championship/'
    | '/api/public/admin/players'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewSlugRoute: typeof CrewSlugRouteWithChildren
  CreaClubRoute: typeof CreaClubRoute
  LoginRoute: typeof LoginRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  ApiPublicAdminPlayersRoute: typeof ApiPublicAdminPlayersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crea-club': {
      id: '/crea-club'
      path: '/crea-club'
      fullPath: '/crea-club'
      preLoaderRoute: typeof CreaClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$crewSlug': {
      id: '/$crewSlug'
      path: '/$crewSlug'
      fullPath: '/$crewSlug'
      preLoaderRoute: typeof CrewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/$crewSlug/': {
      id: '/$crewSlug/'
      path: '/'
      fullPath: '/$crewSlug/'
      preLoaderRoute: typeof CrewSlugIndexRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/$crewSlug/weekly': {
      id: '/$crewSlug/weekly'
      path: '/weekly'
      fullPath: '/$crewSlug/weekly'
      preLoaderRoute: typeof CrewSlugWeeklyRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/tm': {
      id: '/$crewSlug/tm'
      path: '/tm'
      fullPath: '/$crewSlug/tm'
      preLoaderRoute: typeof CrewSlugTmRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/team': {
      id: '/$crewSlug/team'
      path: '/team'
      fullPath: '/$crewSlug/team'
      preLoaderRoute: typeof CrewSlugTeamRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/stagioni': {
      id: '/$crewSlug/stagioni'
      path: '/stagioni'
      fullPath: '/$crewSlug/stagioni'
      preLoaderRoute: typeof CrewSlugStagioniRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/profile': {
      id: '/$crewSlug/profile'
      path: '/profile'
      fullPath: '/$crewSlug/profile'
      preLoaderRoute: typeof CrewSlugProfileRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/players': {
      id: '/$crewSlug/players'
      path: '/players'
      fullPath: '/$crewSlug/players'
      preLoaderRoute: typeof CrewSlugPlayersRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/leaderboard': {
      id: '/$crewSlug/leaderboard'
      path: '/leaderboard'
      fullPath: '/$crewSlug/leaderboard'
      preLoaderRoute: typeof CrewSlugLeaderboardRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/dashboard': {
      id: '/$crewSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$crewSlug/dashboard'
      preLoaderRoute: typeof CrewSlugDashboardRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/black-market': {
      id: '/$crewSlug/black-market'
      path: '/black-market'
      fullPath: '/$crewSlug/black-market'
      preLoaderRoute: typeof CrewSlugBlackMarketRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/azioni': {
      id: '/$crewSlug/azioni'
      path: '/azioni'
      fullPath: '/$crewSlug/azioni'
      preLoaderRoute: typeof CrewSlugAzioniRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/admin': {
      id: '/$crewSlug/admin'
      path: '/admin'
      fullPath: '/$crewSlug/admin'
      preLoaderRoute: typeof CrewSlugAdminRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/championship/': {
      id: '/$crewSlug/championship/'
      path: '/championship'
      fullPath: '/$crewSlug/championship/'
      preLoaderRoute: typeof CrewSlugChampionshipIndexRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/player/$id': {
      id: '/$crewSlug/player/$id'
      path: '/player/$id'
      fullPath: '/$crewSlug/player/$id'
      preLoaderRoute: typeof CrewSlugPlayerIdRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/$crewSlug/championship/$teamId': {
      id: '/$crewSlug/championship/$teamId'
      path: '/championship/$teamId'
      fullPath: '/$crewSlug/championship/$teamId'
      preLoaderRoute: typeof CrewSlugChampionshipTeamIdRouteImport
      parentRoute: typeof CrewSlugRoute
    }
    '/api/public/admin/players': {
      id: '/api/public/admin/players'
      path: '/api/public/admin/players'
      fullPath: '/api/public/admin/players'
      preLoaderRoute: typeof ApiPublicAdminPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrewSlugRouteChildren {
  CrewSlugAdminRoute: typeof CrewSlugAdminRoute
  CrewSlugAzioniRoute: typeof CrewSlugAzioniRoute
  CrewSlugBlackMarketRoute: typeof CrewSlugBlackMarketRoute
  CrewSlugDashboardRoute: typeof CrewSlugDashboardRoute
  CrewSlugLeaderboardRoute: typeof CrewSlugLeaderboardRoute
  CrewSlugPlayersRoute: typeof CrewSlugPlayersRoute
  CrewSlugProfileRoute: typeof CrewSlugProfileRoute
  CrewSlugStagioniRoute: typeof CrewSlugStagioniRoute
  CrewSlugTeamRoute: typeof CrewSlugTeamRoute
  CrewSlugTmRoute: typeof CrewSlugTmRoute
  CrewSlugWeeklyRoute: typeof CrewSlugWeeklyRoute
  CrewSlugIndexRoute: typeof CrewSlugIndexRoute
  CrewSlugChampionshipTeamIdRoute: typeof CrewSlugChampionshipTeamIdRoute
  CrewSlugPlayerIdRoute: typeof CrewSlugPlayerIdRoute
  CrewSlugChampionshipIndexRoute: typeof CrewSlugChampionshipIndexRoute
}

const CrewSlugRouteChildren: CrewSlugRouteChildren = {
  CrewSlugAdminRoute: CrewSlugAdminRoute,
  CrewSlugAzioniRoute: CrewSlugAzioniRoute,
  CrewSlugBlackMarketRoute: CrewSlugBlackMarketRoute,
  CrewSlugDashboardRoute: CrewSlugDashboardRoute,
  CrewSlugLeaderboardRoute: CrewSlugLeaderboardRoute,
  CrewSlugPlayersRoute: CrewSlugPlayersRoute,
  CrewSlugProfileRoute: CrewSlugProfileRoute,
  CrewSlugStagioniRoute: CrewSlugStagioniRoute,
  CrewSlugTeamRoute: CrewSlugTeamRoute,
  CrewSlugTmRoute: CrewSlugTmRoute,
  CrewSlugWeeklyRoute: CrewSlugWeeklyRoute,
  CrewSlugIndexRoute: CrewSlugIndexRoute,
  CrewSlugChampionshipTeamIdRoute: CrewSlugChampionshipTeamIdRoute,
  CrewSlugPlayerIdRoute: CrewSlugPlayerIdRoute,
  CrewSlugChampionshipIndexRoute: CrewSlugChampionshipIndexRoute,
}

const CrewSlugRouteWithChildren = CrewSlugRoute._addFileChildren(
  CrewSlugRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewSlugRoute: CrewSlugRouteWithChildren,
  CreaClubRoute: CreaClubRoute,
  LoginRoute: LoginRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  ApiPublicAdminPlayersRoute: ApiPublicAdminPlayersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
